### ISSUE TITLE
Deletion of AOVs during cleanups

### ISSUE THREAD

**Issue by YasinH** [Kif11/lanoria-assembly#13]
All the AOVs must get deleted during cleanups. Later we will add the required ones to the light file.

**Comment by YasinH** [comment]
```
import mtoa.aovs as aovs
for aov in aovs.AOVInterface().getAOVNodes(names=True):
    aovs.AOVInterface().removeAOVs(aov)
```

**Comment by Kif11** [comment]
@YasinH This is useful! Thanks.

**Comment by YasinH** [comment]
Added to save function

**Comment by Kif11** [comment]
Created `deleteAllAOV()` function in `utils.py`. Use it as a part of **Scene cleanup** procedure.
