### ISSUE TITLE
Save function should be more cautious 

### ISSUE THREAD

**Issue by Kif11** [Kif11/lanoria-assembly#18]
Save function should only work if the scene opened is anim, not light. Otherwise the user may accidentally run it which can screw up the light file!

**Comment by YasinH** [comment]
True, it is supposed to be ran once the user is passed the initial cleanups and is ready to save the light file. The functions getting executed after Save, make changes to the scene which are not desirable and thus, should not be saved into the Light scene.

**Comment by YasinH** [comment]
Let's do this one too so that we can fully close the Save case (should only work if the scene opened is anim)

**Comment by YasinH** [comment]
Also, let's make sure the renderer is set to Arnold during this function before it actually saves the file.

**Comment by Kif11** [comment]
I think we better to do it in some other place. Save function met for saving related stuff.

**Comment by YasinH** [comment]
hmm, during cleanup maybe?
