### ISSUE TITLE
Typo in ENV display layer

### ISSUE THREAD

**Issue by YasinH** [Kif11/lanoria-assembly#19]
<img width="217" alt="screen shot 2016-03-06 at 4 54 25 pm" src="https://cloud.githubusercontent.com/assets/17615272/13554408/2fd391de-e3bc-11e5-81a2-3084ad2bfc9d.png">

**Comment by Kif11** [comment]
This is because you have set with the same name in your scene. I added a new function which utilize QC to delete all of the sets.
![screen shot 2016-03-06 at 11 32 44 am](https://cloud.githubusercontent.com/assets/8003487/13556477/58744e08-e38f-11e5-89fa-d7d1fcd0b854.png)

**Comment by Kif11** [comment]
I implemented a new function that runs as a part of layer_creation script to insure that there is no objects in the scene that has the name reserved by our layers.

```python
def renameColliding(self, name, except_types=[]):
        """
        Look trough all nodes in the scene with the given name an rename it
        as {node_name}_{node_type} to avoid name clashing
        :param name: Name to search for
        :param except_types: Node types to skip
        """
```

**Comment by YasinH** [comment]
As for delete sets and all the other necessary QC checks, what do you think of embedding it inside cleanup function? This one I also need to think a bit more about it whether it is safe to delete all sets or not... but my gut tells me at least the QC checks should be part of cleanup.
Mainly the only QC options required are under General section, first, third and fourth ones

**Comment by Kif11** [comment]
There is a separate issue #7 opened about QC Check. I think, we should combine all QC under one checkbox.
