### ISSUE TITLE
Assign group to layers not working properly

### ISSUE THREAD

**Issue by YasinH** [Kif11/lanoria-assembly#20]
Example scene is promo 2 under test_seq
Nothing gets assigned to the display layers except the character

**Comment by YasinH** [comment]
Additionally, what do you think of changing the Geo type on all assets to On instead of Reference and then set the R flag on the display layers? This way, whenever the lighter wants to select an object from viewport, it's as easy as turning off the R flag from display layer without having to go through all the assets from outliner to find that particular asset.

**Comment by Kif11** [comment]
@YasinH I agree about R flag on layers verses geometry attribute.

**Comment by Kif11** [comment]
I tested it with promo_2. It works. I think it was breaking because of #19  issue.

**Comment by Kif11** [comment]
@YasinH Please test it and close the issue if it works.

**Comment by YasinH** [comment]
About the R flag I'm just worried we might be breaking the pipeline abstract that way. Let's discuss this with Carlos

**Comment by YasinH** [comment]
Carlos agreed on R flag display layer. Let's do it then!

**Comment by YasinH** [comment]
Closing this, creating another one for R flag
