### ISSUE TITLE
Toggle Selection does not toggle properly

### ISSUE THREAD

**Issue by YasinH** [Kif11/lanoria-assembly#22]
Toggle Selection only turns on or off all the check boxes together without considering the current state of check boxes

**Comment by Kif11** [comment]
This is actually how it was planned. How do you see it?

**Comment by YasinH** [comment]
It should work like this
A - ✓
B - ✓
C - x

After Toggle

A - x
B - x
C - ✓

**Comment by Kif11** [comment]
This is called inverse. I made it firs like that and then realize that this is confusing. But if you really want that I can revert it to this behavior.

**Comment by YasinH** [comment]
Yes please! It comes in handy this way more!

**Comment by Kif11** [comment]
OK, this is done. Test it and close this issue if it works.
