### ISSUE TITLE
Update references gets stuck at updating Boy and hangs Maya

### ISSUE THREAD

**Issue by YasinH** [Kif11/lanoria-assembly#25]
bed1015

[+] Switching toySoldierHorse to release shot_ready_v013
[D] Asset crayonA reference release: shot_ready_v012. Latest release: shot_ready_v012
[D] Reference LOD: hi
[D] Asset boy reference release: shot_ready_v058. Latest release: shot_ready_v062
[D] Reference LOD: hi
[+] Switching boy to release shot_ready_v062

**Comment by Kif11** [comment]
I do not experience this issue. It might take a while try to wait longer.

This is my log:
```
[D] Reference LOD: hi
// root : Complete: Got releases for boy 1.000000 // 
[D] Asset boy reference release: shot_ready_v058. Latest release: shot_ready_v062
[D] Reference LOD: hi
[+] Switching boy to release shot_ready_v062
// root : Complete: Updating boy 1.000000 // 
// RepositoryController : _updateView: getting item 'shot_ready/boy.ma' // 
// root : Complete: Downloaded 'shot_ready/boy.ma' 1.000000 // 
// RepositoryController : Got 'shot_ready/boy.ma' v93 // 
// root : Complete: Downloaded 'shot_ready/boy.ma' 1.000000 // 
// root : Complete: Downloaded 'shot_ready/boy.ma' 1.000000 // 
// maya-plugin : Scanner details: /Volumes/EARTH/AnimationMentor/panda/Assets/char/boy/shot_ready_v062/shot_ready, boy.ma, boy, ma // 
// maya-plugin : Choosing Maya scanner // 
// maya-plugin : Processing multiframe /<FRAME> // 
// root : Relativizing '/Volumes/EARTH/AnimationMentor/panda/Assets/char/boy/shot_ready_v062/shot_ready/boy.ma' from '/Volumes/EARTH/AnimationMentor/panda' // 
// root : switchReference: Switching 'boy2' from '$AM_LOCAL_STORAGE_TOP/Assets/char/boy/shot_ready_v058/shot_ready/boy.ma' to '$AM_LOCAL_STORAGE_TOP/Assets/char/boy/shot_ready_v062/shot_ready/boy.ma' // 
# Warning: Reference file path remapped from '$AM_LOCAL_STORAGE_TOP/Assets/char/boy/shot_ready_v062/shot_ready/boy.ma' to '/Volumes/EARTH/AnimationMentor/panda/Assets/char/boy/shot_ready_v062/shot_ready/boy.ma'. # 
// Warning: file: /Volumes/EARTH/AnimationMentor/panda/Assets/char/boy/shot_ready_v062/shot_ready/boy.ma line 1206961: ':miDefaultOptions.message' is already connected to ':mentalrayItemsList.options'. // 
// Warning: file: /Volumes/EARTH/AnimationMentor/panda/Assets/char/boy/shot_ready_v062/shot_ready/boy.ma line 1206962: ':miDefaultFramebuffer.message' is already connected to ':mentalrayItemsList.framebuffers'. // 
# File read in  19.5 seconds. # 
```

**Comment by YasinH** [comment]
I see, might be an issue on my end. What is this line in your log? v93?!

// RepositoryController : Got 'shot_ready/boy.ma' v93 //

**Comment by Kif11** [comment]
What a hack? v93?

**Comment by YasinH** [comment]
I thought it might be the latest working shot-ready but that is at v98 currently! Maybe release 62 of the shot-ready was created from working v93? But I don't get why it is looking for a working version at all!

**Comment by YasinH** [comment]
It finally worked for me after a long time of waiting! But I think it's downloading the release every time even though I have it v62 already! That v93 sounds really suspicious to me though! Have you found out from where it is coming from?

**Comment by Kif11** [comment]
@YasinH Publish your log please.

**Comment by YasinH** [comment]
It looks like your log, I also get this line which I don't get what it is doing. 
// RepositoryController : Got 'shot_ready/boy.ma' v93 //

**Comment by Kif11** [comment]
I'm closing this issue due to lack of information.
