### ISSUE TITLE
export_camera failed on bed1015

### ISSUE THREAD

**Issue by YasinH** [Kif11/lanoria-assembly#27]
Export camera does not work in bed1015, I believe that's because the name of the camera is different in addition to having an unwanted namespace! We should make the function more robust, a good hint is the structure of the camera rig.

**Comment by Kif11** [comment]
The parent constraint failed due to locked transform attributes on the original camera.

**Comment by Kif11** [comment]
This is fix. Now `exportCamera` will unlock transform attributes before performing constraint operations.

**Comment by YasinH** [comment]
Works perfect now. Tested on 1015 and 1020
