### ISSUE TITLE
Preroll does not start at defined range

### ISSUE THREAD

**Issue by YasinH** [Kif11/lanoria-assembly#28]
It seems like when running preroll it doesn't consider the start frame and always starts the preroll at 1001. bed1020

**Comment by Kif11** [comment]
I tested it on bed1020 and it did set the selected start frame for me.
![screen shot 2016-03-15 at 11 19 44 pm](https://cloud.githubusercontent.com/assets/8003487/13803777/96181ce0-eb04-11e5-9e4a-fcdfeda7e2f4.png)

**Comment by Kif11** [comment]
@YasinH Please test it and come back on that.
