### ISSUE TITLE
Pre-roll range

### ISSUE THREAD

**Issue by Kif11** [Kif11/lanoria-assembly#8]
If boy is to far away from its placer the preroll should be extended.

Scene examples:
- hlw1385

**Comment by YasinH** [comment]
Wasn't sure where to put this. Please implement this and let's close the issue. 
Should be exposed as the default value on the UI per open scene. Meaning, it requires a callback if the user opens another scene while having the tool opened.

```
import pymel.core as pm

placerCtrl = pm.ls('*boy*:*CnPlacerCtrl')[0]
RtFoot = pm.ls('*boy*:*RtFootIkCtrl')[0]

placerCtrlPos = pm.datatypes.Vector(pm.xform(placerCtrl, q=True, t=True, ws=True))
RtFootPos = pm.datatypes.Vector(pm.xform(RtFoot, q=True, t=True, ws=True))

ctrlsDist = (placerCtrlPos - RtFootPos).length()

range = 50
if (ctrlsDist > 130):
    range = 100
if (ctrlsDist > 260):
    range = 200
    
print range
```

**Comment by Kif11** [comment]
@YasinH Do you know how to add a callback on Maya scene open? I'm reading [this](http://help.autodesk.com/view/MAYAUL/2015/ENU/?guid=__cpp_ref_class_m_message_html) but it's confusing.

**Comment by Kif11** [comment]
I implemented this feature. It will try to set frame range and preroll start on tool open and new maya scene open.

**Comment by Kif11** [comment]
This is how you register on maya scene open callback:

```python
import maya.api.OpenMaya as om

# Register on open maya update ui callback
om.MSceneMessage.addCallback(om.MSceneMessage.kAfterOpen, self.update_ui)
```

**Comment by YasinH** [comment]
Very cool!
